export const endpoints = {
  GRAPHQL: `${import.meta.env.VITE_APP_SERVER_URL}/api/v1/graphql`,
  STORAGE_URL: `${import.meta.env.STORAGE_URL}`,
};

export const districtOptions = [
  { label: 'Select', value: '' },
  { label: '1-Kumaram Bheem Asifabad', value: '1-Kumaram Bheem Asifabad' },
  { label: '2-Mancherial', value: '2-Mancherial' },
  { label: '3-Adilabad', value: '3-Adilabad' },
  { label: '4-Nirmal', value: '4-Nirmal' },
  { label: '5-Nizamabad', value: '5-Nizamabad' },
  { label: '6-Kamareddy', value: '6-Kamareddy' },
  { label: '7-Jagtial', value: '7-Jagtial' },
  { label: '8-Peddapalli', value: '8-Peddapalli' },
  { label: '9-Karimnagar', value: '9-Karimnagar' },
  { label: '10-Rajanna Sircilla', value: '10-Rajanna Sircilla' },
  { label: '11-Sangareddy', value: '11-Sangareddy' },
  { label: '12-Medak', value: '1-Kumaram Bheem Asifabad' },
  { label: '13-Siddipet', value: '13-Siddipet' },
  { label: '14-Rangareddy', value: '14-Rangareddy' },
  { label: '15-Vikarabad', value: '15-Vikarabad' },
  { label: '16-Medchal Malkajgiri', value: '16-Medchal Malkajgiri' },
  { label: '17-Hyderabad', value: '17-Hyderabad' },
  { label: '18-Mahabubnagar', value: '18-Mahabubnagar' },
  { label: '19-Nagarkurnool', value: '19-Nagarkurnool' },
  { label: '20-Wanaparthy', value: '20-Wanaparthy' },
  { label: '21-Jogulamba Gadwal', value: '21-Jogulamba Gadwal' },
  { label: '22-Nalgonda', value: '22-Nalgonda' },
  { label: '23-Suryapet', value: '23-Suryapet' },
  { label: '24-Yadadri Bhongiri', value: '24-Yadadri Bhongiri' },
  { label: '25-Jangaon', value: '25-Jangaon' },
  { label: '26-Mahabubabad', value: '26-Mahabubabad' },
  { label: '27-Warangal', value: '27-Warangal' },
  { label: '28-Hanumakonda', value: '28-Hanumakonda' },
  { label: '29-Jayashankar Bhupalpalle', value: '29-Jayashankar Bhupalpalle' },
  { label: '30-Bhadradri', value: '30-Bhadradri' },
  { label: '31-Khammam', value: '31-Khammam' },
  { label: '32-Mulugu', value: '32-Mulugu' },
  { label: '33-Narayanpet', value: '33-Narayanpet' },
];

// export const districtOptions = [
//   { label: '1-Kumaram Bheem Asifabad', value: '1' },
//   { label: '2-Mancherial', value: '2' },
//   { label: '3-Adilabad', value: '3' },
//   { label: '4-Nirmal', value: '4' },
//   { label: '5-Nizamabad', value: '5' },
//   { label: '6-Kamareddy', value: '6' },
//   { label: '7-Jagtial', value: '7' },
//   { label: '8-Peddapalli', value: '8' },
//   { label: '9-Karimnagar', value: '9' },
//   { label: '10-Rajanna Sircilla', value: '10' },
//   { label: '11-Sangareddy', value: '11' },
//   { label: '12-Medak', value: '12' },
//   { label: '13-Siddipet', value: '13' },
//   { label: '14-Rangareddy', value: '14' },
//   { label: '15-Vikarabad', value: '15' },
//   { label: '16-Medchal Malkajgiri', value: '16' },
//   { label: '18-Mahabubnagar', value: '18' },
//   { label: '19-Nagarkurnool', value: '19' },
//   { label: '20-Wanaparthy', value: '20' },
//   { label: '21-Jogulamba Gadwal', value: '21' },
//   { label: '22-Nalgonda', value: '22' },
//   { label: '23-Suryapet', value: '23' },
//   { label: '24-Yadadri Bhongiri', value: '24' },
//   { label: '25-Jangaon', value: '25' },
//   { label: '26-Mahabubabad', value: '26' },
//   { label: '27-Warangal', value: '27' },
//   { label: '28-Hanumakonda', value: '28' },
//   { label: '29-Jayashankar Bhupalpalle', value: '29' },
//   { label: '30-Bhadradri', value: '30' },
//   { label: '31-Khammam', value: '31' },
//   { label: '32-Mulugu', value: '32' },
//   { label: '33-Narayanpet', value: '33' },
// ];

// export const assemblyConstituenciesOptions = {
//   1: ['1-Sirpur', '5-Asifabad(ST)'], // Replace 'Assembly1', 'Assembly2', 'Assembly3' with actual assembly constituency names
//   2: ['2-Chennur(SC)', '3-Bellampalli(SC)', '4-Mancherial'],
//   3: ['7-Adilabad', '8-Boath(ST)'],
//   4: ['6-Khanapur(ST)', '9-Nirmal', '10-Mudhole'],
//   5: [
//     '11-Armur',
//     '12-Bodhan',
//     '14-Banswada',
//     '17-Nizamabad (Urban)',
//     '18-Nizamabad (Rural)',
//     '19-Balkonda',
//   ],
//   6: ['13-Jukkal(SC)', '15-Yellareddy', '16-Kamareddy'],
//   7: ['20-Koratla', '21-Jagtial', '22-Dharmapuri(SC)'],
//   8: ['23-Ramagundam', '24-Manthani', '25-Peddapalle'],
//   9: [
//     '26-Karimnagar',
//     '27-Choppadandi(SC)',
//     '30-Manakondur(SC)',
//     '31-Huzurabad',
//   ],
//   10: ['28-Vemulawada', '29-Sircilla'],
//   11: [
//     '35-Narayankhed',
//     '36-Andole(SC)',
//     '38-Zaheerabad(SC)',
//     '39-Sangareddy',
//     '40-Patancheru',
//   ],
//   12: ['34-Medak', '37-Narsapur'],
//   13: ['32-Husnabad', '33-Siddipet', '41-Dubbak', '42-Gajwel'],
//   14: [
//     '48-Ibrahimpatnam',
//     '49-Lal Bahadur Nagar',
//     '50-Maheswaram',
//     '51-Rajendranagar',
//     '52-Serilingampally',
//     '53-Chevella(SC)',
//     '83-Kalwakurthy',
//     '84-Shadnagar',
//   ],
//   15: ['54-Pargi', '55-Vicarabad(SC)', '56-Tandur', '72-Kodangal'],
//   16: [
//     '43-Medchal',
//     '44-Malkajgiri',
//     '45-Quthbullapur',
//     '46-Kukatpally',
//     '47-Uppal',
//   ],
//   17: [
//     '57-Musheerabad',
//     '58-Malakpet',
//     '59-Amberpet',
//     '60-Khairatabad',
//     '61-Jubilee Hills',
//     '62-Sanathnagar',
//     '63-Nampally',
//     '64-Karwan',
//     '65-Goshamahal',
//     '66-Charminar',
//     '67-Chandrayangutta',
//     '68-Yakutpura',
//     '69-Bahadurpura',
//     '70-Secunderabad',
//     '71-Secunderabad Cantt(SC)',
//   ],
//   18: ['74-Mahbubnagar', '75-Jadcherla', '76-Devarkadra'],
//   19: ['81-Nagarkurnool', '82-Achampet(SC)', '85-Kollapur'],
//   20: ['78-Wanaparthy'],
//   21: ['79-Gadwal', '80-Alampur(SC)(SC)'],
//   22: [
//     '86-Devarakonda(ST)',
//     '87-Nagarjuna Sagar',
//     '88-Miryalaguda',
//     '92-Nalgonda',
//     '93-Munugode',
//     '95-Nakrekal(SC)',
//   ],
//   23: ['89-Huzurnagar', '90-Kodad', '91-Suryapet', '96-Thungathurthi(SC)'],
//   24: ['94-Bhongir', '97-Alair'],
//   25: ['98-Jangoan', '99-Ghanpur (Station)(SC)', '100-Palakurthi'],
//   26: ['101-Dornakal(ST)', '102-Mahabubabad(ST)'],
//   27: ['103-Narsampet', '106-Warangal East', '107-Waradhanapet(SC)'],
//   28: ['104-Parkal', '105-Warangal West'],
//   29: ['108-Bhupalpalle'],
//   30: [
//     '110-Pinapaka(ST)',
//     '111-Yellandu(ST)',
//     '117-Kothagudem',
//     '118-Aswaraopeta(ST)',
//     '119-Bhadrachalam(ST)',
//   ],
//   31: [
//     '112-Khammam',
//     '113-Palair',
//     '114-Madhira(SC)',
//     '115-Wyra(ST)',
//     '116-Sathupalle(SC)',
//   ],
//   32: ['109-Mulug(ST)'],
//   33: ['73-Narayanpet', '77-Makthal'],

//   // Add mappings for other districts
// };

export const assemblyConstituenciesOptions = {
  1: ['1-Sirpur', '5-Asifabad(ST)'], // Replace 'Assembly1', 'Assembly2', 'Assembly3' with actual assembly constituency names
  2: ['2-Chennur(SC)', '3-Bellampalli(SC)', '4-Mancherial'],
  3: ['7-Adilabad', '8-Boath(ST)'],
  4: ['6-Khanapur(ST)', '9-Nirmal', '10-Mudhole'],
  5: [
    '11-Armur',
    '12-Bodhan',
    '14-Banswada',
    '17-Nizamabad (Urban)',
    '18-Nizamabad (Rural)',
    '19-Balkonda',
  ],
  6: ['13-Jukkal(SC)', '15-Yellareddy', '16-Kamareddy'],
  7: ['20-Koratla', '21-Jagtial', '22-Dharmapuri(SC)'],
  8: ['23-Ramagundam', '24-Manthani', '25-Peddapalle'],
  9: [
    '26-Karimnagar',
    '27-Choppadandi(SC)',
    '30-Manakondur(SC)',
    '31-Huzurabad',
  ],
  10: ['28-Vemulawada', '29-Sircilla'],
  11: [
    '35-Narayankhed',
    '36-Andole(SC)',
    '38-Zaheerabad(SC)',
    '39-Sangareddy',
    '40-Patancheru',
  ],
  12: ['34-Medak', '37-Narsapur'],
  13: ['32-Husnabad', '33-Siddipet', '41-Dubbak', '42-Gajwel'],
  14: [
    '48-Ibrahimpatnam',
    '49-Lal Bahadur Nagar',
    '50-Maheswaram',
    '51-Rajendranagar',
    '52-Serilingampally',
    '53-Chevella(SC)',
    '83-Kalwakurthy',
    '84-Shadnagar',
  ],
  15: ['54-Pargi', '55-Vicarabad(SC)', '56-Tandur', '72-Kodangal'],
  16: [
    '43-Medchal',
    '44-Malkajgiri',
    '45-Quthbullapur',
    '46-Kukatpally',
    '47-Uppal',
  ],
  17: [
    '57-Musheerabad',
    '58-Malakpet',
    '59-Amberpet',
    '60-Khairatabad',
    '61-Jubilee Hills',
    '62-Sanathnagar',
    '63-Nampally',
    '64-Karwan',
    '65-Goshamahal',
    '66-Charminar',
    '67-Chandrayangutta',
    '68-Yakutpura',
    '69-Bahadurpura',
    '70-Secunderabad',
    '71-Secunderabad Cantt(SC)',
  ],
  18: ['74-Mahbubnagar', '75-Jadcherla', '76-Devarkadra'],
  19: ['81-Nagarkurnool', '82-Achampet(SC)', '85-Kollapur'],
  20: ['78-Wanaparthy'],
  21: ['79-Gadwal', '80-Alampur(SC)(SC)'],
  22: [
    '86-Devarakonda(ST)',
    '87-Nagarjuna Sagar',
    '88-Miryalaguda',
    '92-Nalgonda',
    '93-Munugode',
    '95-Nakrekal(SC)',
  ],
  23: ['89-Huzurnagar', '90-Kodad', '91-Suryapet', '96-Thungathurthi(SC)'],
  24: ['94-Bhongir', '97-Alair'],
  25: ['98-Jangoan', '99-Ghanpur (Station)(SC)', '100-Palakurthi'],
  26: ['101-Dornakal(ST)', '102-Mahabubabad(ST)'],
  27: ['103-Narsampet', '106-Warangal East', '107-Waradhanapet(SC)'],
  28: ['104-Parkal', '105-Warangal West'],
  29: ['108-Bhupalpalle'],
  30: [
    '110-Pinapaka(ST)',
    '111-Yellandu(ST)',
    '117-Kothagudem',
    '118-Aswaraopeta(ST)',
    '119-Bhadrachalam(ST)',
  ],
  31: [
    '112-Khammam',
    '113-Palair',
    '114-Madhira(SC)',
    '115-Wyra(ST)',
    '116-Sathupalle(SC)',
  ],
  32: ['109-Mulug(ST)'],
  33: ['73-Narayanpet', '77-Makthal'],

  // Add mappings for other districts
};
